// Hand-curated CPU and RAM presets for the tokens/sec estimator.
// GPU presets live in gpu-data.json (generated by scripts/build-gpu-list.js).
//
// CPU FP16 FLOPS approximation: cores × boostGHz × FLOPsPerCycle, where
// FLOPsPerCycle is the effective FP16 throughput per core per cycle using
// the widest available SIMD (AVX2 = 16, AVX-512 = 32, NEON = 8, Zen 1/+
// AVX2 on 128-bit FPU = 8). Same formula used by gguf-parser-go's docs
// (README.md §CPU FLOPS), pessimistic vs. real-world tensor-core-equivalent
// CPU kernels but good enough as a decode-time lower bound (decode is
// bandwidth-bound anyway).
//
// RAM bandwidth presets are theoretical peaks per channel-configuration.

export const CPU_PRESETS = [
  // ── Apple Silicon ──
  // FP16 FLOPS for M-series CPU is per-core NEON (128-bit = 8 FP16 FMAs),
  // performance cores only (efficiency cores contribute ~0.3x).
  { id: 'apple-m4-max',    name: 'Apple M4 Max (10P)',   vendor: 'Apple',  fp16Tflops: 0.32,  defaultRamBwGBps: 546 },
  { id: 'apple-m4-pro',    name: 'Apple M4 Pro (8P)',    vendor: 'Apple',  fp16Tflops: 0.26,  defaultRamBwGBps: 273 },
  { id: 'apple-m4',        name: 'Apple M4 (4P)',        vendor: 'Apple',  fp16Tflops: 0.13,  defaultRamBwGBps: 120 },
  { id: 'apple-m3-ultra',  name: 'Apple M3 Ultra (24P)', vendor: 'Apple',  fp16Tflops: 0.70,  defaultRamBwGBps: 819 },
  { id: 'apple-m3-max',    name: 'Apple M3 Max (12P)',   vendor: 'Apple',  fp16Tflops: 0.35,  defaultRamBwGBps: 400 },
  { id: 'apple-m3-pro',    name: 'Apple M3 Pro (6P)',    vendor: 'Apple',  fp16Tflops: 0.18,  defaultRamBwGBps: 150 },
  { id: 'apple-m3',        name: 'Apple M3 (4P)',        vendor: 'Apple',  fp16Tflops: 0.12,  defaultRamBwGBps: 100 },
  { id: 'apple-m2-ultra',  name: 'Apple M2 Ultra (16P)', vendor: 'Apple',  fp16Tflops: 0.45,  defaultRamBwGBps: 819 },
  { id: 'apple-m2-max',    name: 'Apple M2 Max (8P)',    vendor: 'Apple',  fp16Tflops: 0.22,  defaultRamBwGBps: 400 },
  { id: 'apple-m2-pro',    name: 'Apple M2 Pro (8P)',    vendor: 'Apple',  fp16Tflops: 0.22,  defaultRamBwGBps: 200 },
  { id: 'apple-m2',        name: 'Apple M2 (4P)',        vendor: 'Apple',  fp16Tflops: 0.11,  defaultRamBwGBps: 100 },
  { id: 'apple-m1-ultra',  name: 'Apple M1 Ultra (16P)', vendor: 'Apple',  fp16Tflops: 0.41,  defaultRamBwGBps: 819 },
  { id: 'apple-m1-max',    name: 'Apple M1 Max (8P)',    vendor: 'Apple',  fp16Tflops: 0.21,  defaultRamBwGBps: 400 },
  { id: 'apple-m1-pro',    name: 'Apple M1 Pro (8P)',    vendor: 'Apple',  fp16Tflops: 0.21,  defaultRamBwGBps: 200 },
  { id: 'apple-m1',        name: 'Apple M1 (4P)',        vendor: 'Apple',  fp16Tflops: 0.10,  defaultRamBwGBps: 68 },

  // ── AMD Ryzen desktop (Zen 1 / Zen+) ──
  // AVX2 on 128-bit native FPU (256-bit cracked into 2 µops) → 8 FP16/cycle.
  { id: 'ryzen-2700x',  name: 'Ryzen 7 2700X (Zen+, 8C)',     vendor: 'AMD', fp16Tflops: 0.28, defaultRamBwGBps: 47 },
  { id: 'ryzen-2600x',  name: 'Ryzen 5 2600X (Zen+, 6C)',     vendor: 'AMD', fp16Tflops: 0.20, defaultRamBwGBps: 47 },
  { id: 'ryzen-1800x',  name: 'Ryzen 7 1800X (Zen 1, 8C)',    vendor: 'AMD', fp16Tflops: 0.26, defaultRamBwGBps: 42 },
  { id: 'ryzen-1600x',  name: 'Ryzen 5 1600X (Zen 1, 6C)',    vendor: 'AMD', fp16Tflops: 0.19, defaultRamBwGBps: 42 },

  // ── AMD Ryzen desktop (Zen 2-5) ──
  // AVX2 only on Zen 2/3 (16 FP16/cycle), AVX-512 on Zen 4/5 (32 FP16/cycle).
  { id: 'ryzen-9950x',  name: 'Ryzen 9 9950X (Zen 5, 16C)',   vendor: 'AMD', fp16Tflops: 2.80, defaultRamBwGBps: 83 },
  { id: 'ryzen-9900x',  name: 'Ryzen 9 9900X (Zen 5, 12C)',   vendor: 'AMD', fp16Tflops: 2.00, defaultRamBwGBps: 83 },
  { id: 'ryzen-9700x',  name: 'Ryzen 7 9700X (Zen 5, 8C)',    vendor: 'AMD', fp16Tflops: 1.35, defaultRamBwGBps: 83 },
  { id: 'ryzen-9600x',  name: 'Ryzen 5 9600X (Zen 5, 6C)',    vendor: 'AMD', fp16Tflops: 1.04, defaultRamBwGBps: 90 },
  { id: 'ryzen-7950x',  name: 'Ryzen 9 7950X (Zen 4, 16C)',   vendor: 'AMD', fp16Tflops: 2.75, defaultRamBwGBps: 83 },
  { id: 'ryzen-7950x3d',name: 'Ryzen 9 7950X3D (Zen 4, 16C)', vendor: 'AMD', fp16Tflops: 2.50, defaultRamBwGBps: 83 },
  { id: 'ryzen-7900x',  name: 'Ryzen 9 7900X (Zen 4, 12C)',   vendor: 'AMD', fp16Tflops: 2.05, defaultRamBwGBps: 83 },
  { id: 'ryzen-7700x',  name: 'Ryzen 7 7700X (Zen 4, 8C)',    vendor: 'AMD', fp16Tflops: 1.40, defaultRamBwGBps: 83 },
  { id: 'ryzen-7600x',  name: 'Ryzen 5 7600X (Zen 4, 6C)',    vendor: 'AMD', fp16Tflops: 1.02, defaultRamBwGBps: 83 },
  { id: 'ryzen-5950x',  name: 'Ryzen 9 5950X (Zen 3, 16C)',   vendor: 'AMD', fp16Tflops: 1.30, defaultRamBwGBps: 51 },
  { id: 'ryzen-5900x',  name: 'Ryzen 9 5900X (Zen 3, 12C)',   vendor: 'AMD', fp16Tflops: 0.95, defaultRamBwGBps: 51 },
  { id: 'ryzen-5800x',  name: 'Ryzen 7 5800X (Zen 3, 8C)',    vendor: 'AMD', fp16Tflops: 0.65, defaultRamBwGBps: 51 },
  { id: 'ryzen-5700x',  name: 'Ryzen 7 5700X (Zen 3, 8C)',    vendor: 'AMD', fp16Tflops: 0.59, defaultRamBwGBps: 51 },
  { id: 'ryzen-5600x',  name: 'Ryzen 5 5600X (Zen 3, 6C)',    vendor: 'AMD', fp16Tflops: 0.44, defaultRamBwGBps: 51 },
  { id: 'ryzen-3950x',  name: 'Ryzen 9 3950X (Zen 2, 16C)',   vendor: 'AMD', fp16Tflops: 1.10, defaultRamBwGBps: 47 },
  { id: 'ryzen-3900x',  name: 'Ryzen 9 3900X (Zen 2, 12C)',   vendor: 'AMD', fp16Tflops: 0.88, defaultRamBwGBps: 51 },
  { id: 'ryzen-3700x',  name: 'Ryzen 7 3700X (Zen 2, 8C)',    vendor: 'AMD', fp16Tflops: 0.56, defaultRamBwGBps: 51 },
  { id: 'ryzen-3600',   name: 'Ryzen 5 3600 (Zen 2, 6C)',     vendor: 'AMD', fp16Tflops: 0.40, defaultRamBwGBps: 51 },

  // ── AMD Threadripper (HEDT / workstation) ──
  // Quad-channel DDR4 on X399/TRX40; 8-channel on sWRX8/sTR5.
  { id: 'tr-pro-7995wx', name: 'Threadripper Pro 7995WX (Zen 4, 96C)', vendor: 'AMD', fp16Tflops: 15.67, defaultRamBwGBps: 333 },
  { id: 'tr-pro-5995wx', name: 'Threadripper Pro 5995WX (Zen 3, 64C)', vendor: 'AMD', fp16Tflops: 4.60,  defaultRamBwGBps: 205 },
  { id: 'tr-3990x',      name: 'Threadripper 3990X (Zen 2, 64C)',      vendor: 'AMD', fp16Tflops: 4.40,  defaultRamBwGBps: 102 },
  { id: 'tr-3970x',      name: 'Threadripper 3970X (Zen 2, 32C)',      vendor: 'AMD', fp16Tflops: 2.30,  defaultRamBwGBps: 102 },
  { id: 'tr-2990wx',     name: 'Threadripper 2990WX (Zen+, 32C)',      vendor: 'AMD', fp16Tflops: 1.08,  defaultRamBwGBps: 94 },
  { id: 'tr-1950x',      name: 'Threadripper 1950X (Zen 1, 16C)',      vendor: 'AMD', fp16Tflops: 0.51,  defaultRamBwGBps: 85 },

  // ── Intel Core desktop (6th-8th gen, AVX2 only) ──
  // Skylake/Kaby Lake/Coffee Lake — AVX2 at 16 FP16/cycle, no AVX-512.
  { id: 'i7-8700k',        name: 'Core i7-8700K (Coffee Lake, 6C)',  vendor: 'Intel', fp16Tflops: 0.45, defaultRamBwGBps: 42 },
  { id: 'i5-8600k',        name: 'Core i5-8600K (Coffee Lake, 6C)',  vendor: 'Intel', fp16Tflops: 0.41, defaultRamBwGBps: 42 },
  { id: 'i7-7700k',        name: 'Core i7-7700K (Kaby Lake, 4C)',    vendor: 'Intel', fp16Tflops: 0.29, defaultRamBwGBps: 38 },
  { id: 'i5-7600k',        name: 'Core i5-7600K (Kaby Lake, 4C)',    vendor: 'Intel', fp16Tflops: 0.27, defaultRamBwGBps: 38 },
  { id: 'i7-6700k',        name: 'Core i7-6700K (Skylake, 4C)',      vendor: 'Intel', fp16Tflops: 0.27, defaultRamBwGBps: 34 },
  { id: 'i5-6600k',        name: 'Core i5-6600K (Skylake, 4C)',      vendor: 'Intel', fp16Tflops: 0.25, defaultRamBwGBps: 34 },

  // ── Intel Core desktop (9th-14th gen + Core Ultra) ──
  // AVX-512 on 11th-gen desktop (Rocket Lake) only; dropped on 12-14th hybrid;
  // Core Ultra 200S has AVX-512 again (Arrow Lake P-cores).
  { id: 'core-ultra-285k', name: 'Core Ultra 9 285K (8P+16E)',   vendor: 'Intel', fp16Tflops: 2.40, defaultRamBwGBps: 90 },
  { id: 'i9-14900k',       name: 'Core i9-14900K (8P+16E)',      vendor: 'Intel', fp16Tflops: 1.40, defaultRamBwGBps: 90 },
  { id: 'i9-13900k',       name: 'Core i9-13900K (8P+16E)',      vendor: 'Intel', fp16Tflops: 1.35, defaultRamBwGBps: 90 },
  { id: 'i5-14600k',       name: 'Core i5-14600K (6P+8E)',       vendor: 'Intel', fp16Tflops: 0.90, defaultRamBwGBps: 90 },
  { id: 'i7-13700k',       name: 'Core i7-13700K (8P+8E)',       vendor: 'Intel', fp16Tflops: 1.15, defaultRamBwGBps: 90 },
  { id: 'i9-12900k',       name: 'Core i9-12900K (8P+8E)',       vendor: 'Intel', fp16Tflops: 1.10, defaultRamBwGBps: 77 },
  { id: 'i5-12600k',       name: 'Core i5-12600K (6P+4E)',       vendor: 'Intel', fp16Tflops: 0.70, defaultRamBwGBps: 77 },
  { id: 'i9-11900k',       name: 'Core i9-11900K (8C, AVX-512)', vendor: 'Intel', fp16Tflops: 1.30, defaultRamBwGBps: 51 },
  { id: 'i7-11700k',       name: 'Core i7-11700K (8C, AVX-512)', vendor: 'Intel', fp16Tflops: 1.28, defaultRamBwGBps: 51 },
  { id: 'i5-11600k',       name: 'Core i5-11600K (6C, AVX-512)', vendor: 'Intel', fp16Tflops: 0.94, defaultRamBwGBps: 51 },
  { id: 'i9-10900k',       name: 'Core i9-10900K (10C)',         vendor: 'Intel', fp16Tflops: 0.80, defaultRamBwGBps: 45 },
  { id: 'i5-10600k',       name: 'Core i5-10600K (6C)',          vendor: 'Intel', fp16Tflops: 0.46, defaultRamBwGBps: 45 },
  { id: 'i9-9900k',        name: 'Core i9-9900K (8C)',           vendor: 'Intel', fp16Tflops: 0.65, defaultRamBwGBps: 42 },
  { id: 'i5-9600k',        name: 'Core i5-9600K (6C)',           vendor: 'Intel', fp16Tflops: 0.44, defaultRamBwGBps: 42 },

  // ── Server ──
  { id: 'epyc-9754',       name: 'EPYC 9754 (Zen 4c, 128C)',        vendor: 'AMD',   fp16Tflops: 18.5, defaultRamBwGBps: 460 },
  { id: 'epyc-9654',       name: 'EPYC 9654 (Zen 4, 96C)',          vendor: 'AMD',   fp16Tflops: 15.0, defaultRamBwGBps: 460 },
  { id: 'epyc-7763',       name: 'EPYC 7763 (Zen 3, 64C)',          vendor: 'AMD',   fp16Tflops: 5.90, defaultRamBwGBps: 205 },
  { id: 'epyc-7742',       name: 'EPYC 7742 (Rome/Zen 2, 64C)',     vendor: 'AMD',   fp16Tflops: 3.48, defaultRamBwGBps: 205 },
  { id: 'epyc-7601',       name: 'EPYC 7601 (Naples/Zen 1, 32C)',   vendor: 'AMD',   fp16Tflops: 0.82, defaultRamBwGBps: 170 },
  { id: 'xeon-8592',       name: 'Xeon 8592+ (Emerald, 64C)',       vendor: 'Intel', fp16Tflops: 13.0, defaultRamBwGBps: 307 },
  { id: 'xeon-8480',       name: 'Xeon 8480+ (Sapphire, 56C)',      vendor: 'Intel', fp16Tflops: 11.0, defaultRamBwGBps: 307 },
  { id: 'xeon-8380',       name: 'Xeon 8380 (Ice Lake, 40C)',       vendor: 'Intel', fp16Tflops: 6.40, defaultRamBwGBps: 205 },
  { id: 'xeon-8280',       name: 'Xeon 8280 (Cascade Lake, 28C)',   vendor: 'Intel', fp16Tflops: 3.58, defaultRamBwGBps: 141 },
  { id: 'xeon-8180',       name: 'Xeon 8180 (Skylake-SP, 28C)',     vendor: 'Intel', fp16Tflops: 3.40, defaultRamBwGBps: 128 },
  { id: 'xeon-e5-2690v4',  name: 'Xeon E5-2690 v4 (Broadwell, 14C)',vendor: 'Intel', fp16Tflops: 0.78, defaultRamBwGBps: 77 },
];

// RAM bandwidth presets. "Dual-channel" numbers are typical desktop configs;
// server configs list the channel count. Apple M-series is unified memory
// (same as the CPU preset's defaultRamBwGBps) — listed here for manual use.
export const RAM_PRESETS = [
  { id: 'ddr5-8000-dc',  name: 'DDR5-8000 dual-channel',    bandwidthGBps: 128 },
  { id: 'ddr5-7200-dc',  name: 'DDR5-7200 dual-channel',    bandwidthGBps: 115 },
  { id: 'ddr5-6400-dc',  name: 'DDR5-6400 dual-channel',    bandwidthGBps: 102 },
  { id: 'ddr5-6000-dc',  name: 'DDR5-6000 dual-channel',    bandwidthGBps: 96 },
  { id: 'ddr5-5600-dc',  name: 'DDR5-5600 dual-channel',    bandwidthGBps: 90 },
  { id: 'ddr5-4800-dc',  name: 'DDR5-4800 dual-channel',    bandwidthGBps: 77 },
  { id: 'ddr4-3600-dc',  name: 'DDR4-3600 dual-channel',    bandwidthGBps: 58 },
  { id: 'ddr4-3200-dc',  name: 'DDR4-3200 dual-channel',    bandwidthGBps: 51 },
  { id: 'ddr4-2933-dc',  name: 'DDR4-2933 dual-channel',    bandwidthGBps: 47 },
  { id: 'ddr4-2666-dc',  name: 'DDR4-2666 dual-channel',    bandwidthGBps: 42 },
  { id: 'ddr4-2400-dc',  name: 'DDR4-2400 dual-channel',    bandwidthGBps: 38 },
  { id: 'ddr4-2133-dc',  name: 'DDR4-2133 dual-channel',    bandwidthGBps: 34 },

  { id: 'ddr4-3200-4ch', name: 'DDR4-3200 quad-channel (sTRX4)',    bandwidthGBps: 102 },
  { id: 'ddr4-2666-4ch', name: 'DDR4-2666 quad-channel (X299/X399)',bandwidthGBps: 85 },

  { id: 'ddr5-4800-8ch', name: 'DDR5-4800 8-channel server',bandwidthGBps: 307 },
  { id: 'ddr5-5600-8ch', name: 'DDR5-5600 8-channel server',bandwidthGBps: 358 },
  { id: 'ddr5-6400-12ch',name: 'DDR5-6400 12-channel EPYC', bandwidthGBps: 614 },
  { id: 'ddr4-3200-8ch', name: 'DDR4-3200 8-channel server',bandwidthGBps: 205 },
  { id: 'ddr4-2666-8ch', name: 'DDR4-2666 8-channel (EPYC Naples)', bandwidthGBps: 170 },
  { id: 'ddr4-2666-6ch', name: 'DDR4-2666 6-channel (Skylake-SP)',  bandwidthGBps: 128 },

  { id: 'lpddr5x-8533',  name: 'LPDDR5X-8533 quad-channel', bandwidthGBps: 273 },
  { id: 'lpddr5-6400-qc',name: 'LPDDR5-6400 quad-channel',  bandwidthGBps: 205 },

  { id: 'apple-um-68',   name: 'Apple unified 68 GB/s (M1 base)',     bandwidthGBps: 68 },
  { id: 'apple-um-120',  name: 'Apple unified 120 GB/s (M4 base)',    bandwidthGBps: 120 },
  { id: 'apple-um-200',  name: 'Apple unified 200 GB/s (M2 Pro)',     bandwidthGBps: 200 },
  { id: 'apple-um-273',  name: 'Apple unified 273 GB/s (M4 Pro)',     bandwidthGBps: 273 },
  { id: 'apple-um-400',  name: 'Apple unified 400 GB/s (M1/2/3 Max)', bandwidthGBps: 400 },
  { id: 'apple-um-546',  name: 'Apple unified 546 GB/s (M4 Max)',     bandwidthGBps: 546 },
  { id: 'apple-um-819',  name: 'Apple unified 819 GB/s (M1/2/3 Ultra)', bandwidthGBps: 819 },
];

export function findCpuPreset(query) {
  if (!query) return null;
  const q = query.toLowerCase();
  return CPU_PRESETS.find(p => p.id === q)
      || CPU_PRESETS.find(p => p.name.toLowerCase() === q)
      || CPU_PRESETS.find(p => p.name.toLowerCase().includes(q))
      || null;
}

export function findRamPreset(query) {
  if (!query) return null;
  const q = query.toLowerCase();
  return RAM_PRESETS.find(p => p.id === q)
      || RAM_PRESETS.find(p => p.name.toLowerCase() === q)
      || RAM_PRESETS.find(p => p.name.toLowerCase().includes(q))
      || null;
}
